/**
 * Event generated for keyboard events on a hit region.
 */
export interface KeyboardHitEvent {

    /**
     * Physical key on the keyboard.
     */
    code: string;

    /**
     * Character generated by pressing the key.
     */
    key: string;

    /**
     * Indicates whether the alt/option key was pressed.
     */
    altKey: boolean;

    /**
     * Indicates whether the ctrl key was pressed.
     */
    ctrlKey: boolean;

    /**
     * Indicates whether the meta key was pressed.
     */
    metaKey: boolean;

    /**
     * Indicates whether the shift key was pressed.
     */
    shiftKey: boolean;
}
