theme: null

# Dist used in examples
dist: '/timeline/assets/timeline.js'
baseurl: /timeline

collections:
  api:
    output: true
    permalink: /:collection/:path/
  drawables:
    output: true
    permalink: /:collection/:path/
