import { TimeRange } from './TimeRange';

/**
 * Tag interface for all events generated by a Timeline instance.
 */
export interface TimelineEvent {
}

/**
 * Event generated when the viewport has changed.
 */
export interface ViewportChangeEvent extends TimelineEvent {
    /**
     * Left bound of the visible time range
     */
    start: number;

    /**
     * Right bound of the visible time range
     */
    stop: number;
}

/**
 * Event generated when the mouse is moving over
 * the viewport.
 */
export interface ViewportMouseMoveEvent extends TimelineEvent {
    /**
     * Horizontal coordinate of the mouse pointer, relative to
     * the browser page.
     */
    clientX: number;

    /**
     * Vertical coordinate of the mouse pointer, relative to the
     * browser page.
     */
    clientY: number;

    /**
     * Time matching with the coordinates of the mouse pointer.
     */
    time: number;
}

/**
 * Event generated when the mouse is moving outside the viewport.
 */
export interface ViewportMouseOutEvent extends TimelineEvent {
    /**
     * Horizontal coordinate of the mouse pointer, relative to
     * the browser page.
     */
    clientX: number;

    /**
     * Vertical coordinate of the mouse pointer, relative to the
     * browser page.
     */
    clientY: number;
}

/**
 * Event generated when the selected range has changed.
 */
export interface ViewportSelectionEvent extends TimelineEvent {
    /**
     * Selected time range (if any).
     */
    selection?: TimeRange;
}

export type TimelineEventHandlers = {
    'viewportchange': Array<(ev: ViewportChangeEvent) => void>;
    'viewportmousemove': Array<(ev: ViewportMouseMoveEvent) => void>;
    'viewportmouseout': Array<(ev: ViewportMouseOutEvent) => void>;
    'viewportselection': Array<(ev: ViewportSelectionEvent) => void>;
};
