name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: npm install and build
        run: |
          npm ci
          npm run build
          npm run tsdoc
        env:
          CI: true

      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          npm publish --access public

      - name: Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: true # Only publish after manual trigger
